name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust for your project version

      - name: Publish Blazor WASM
        run: |
            dotnet publish -c Release --output build
            mv build/bin/Release/net8.0/browser-wasm/publish/wwwroot build/output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
